global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']

  - job_name: juice-agent
    static_configs:
      - targets: ['juice-agent:9101']

  - job_name: gpu
    metrics_path: /metrics
    static_configs:
      - targets: ['dcgm-exporter:9400']

  - job_name: pw-agent
    metrics_path: /metrics
    scrape_interval: 20s
    static_configs:
      - targets: ['172.17.0.1:9091']
        labels:
          exported-by: pw-agent
